### ISSUE TITLE
fix adobe pdf print 

### ISSUE THREAD

**Issue by huizichin** [E-Soda/CCStopper#1]
![image](https://user-images.githubusercontent.com/16850884/118433448-a1168e80-b70d-11eb-9f29-7b21731cbe67.png)
maybe add this into the script and an option to disable update

**Comment by E-Soda** [comment]
Could you provide more info and provide the link to the original source? Also please clarify disabling updates. If it is about disabling CC app updates, I do not know of a way to do that within a batch/PowerShell script.

A few thoughts/things that I'd like to write down:
- I would need to provide an option to create a system restore point before editing the registry
- Need to check if Acrobat DC is installed before editing the registry
- Also provide an option to restart the PC after 

Anyways, thanks for the issue, I'll see what I can do!

**Comment by E-Soda** [comment]
Added the acrobat fix, along with an update checker
