### ISSUE TITLE
No apps or processes are closed and it looks like it errors out before returning to the original menu

### ISSUE THREAD

**Issue by Twelveis** [E-Soda/CCStopper#6]
The argument '.\scripts\ProcessKill.ps1' to the -File parameter does not exist. Provide the path to an existing

file as an argument to the -File parameter.

This appears in red for a frame before going back to the original menu and no apps/processes are closed.

**Comment by E-Soda** [comment]
This issue is fixed in the 1.01 update, but you will need to answer with `a` when you use the PorcessKill script.
